### PR TITLE
[ci] add automation to manage tool versions in Makefile

### PR DESCRIPTION
**Pull request by andrewkroh**
This adds an additional updatecli configuration to update goimports and golicenser to the latest available releases.

The job runs periodically and opens pull requests. And example is #79.

### CODE REVIEW

**Comment by andrewkroh** [comment]
That build failure is not related to this change. I think it is due to a lack of sanitization of the branch name. It passes the branch name through as part of a docker tag.

**Review by efd6 — COMMENTED** [review]
Is there a reason not to use the go.mod to pin the versions?

ref:https://www.updatecli.io/docs/plugins/autodiscovery/golang/

**Comment by andrewkroh** [comment]
You mean the "tools.go" route where you `import _ "module/tool"` so that it ends up tracked in go.mod?

**Comment by efd6** [comment]
Yep

**Comment by andrewkroh** [comment]
I will open a new PR to add a `tools.go`.

**Pull request closed without merging**
